module SeedCategorySectionMappings
  def self.seed
    category_sections.each do |ary|
      CategorySectionMapping.create(
        category: ary[0],
        subcategory: ary[1],
        section: ary[2]
      )
    end
  end

  def self.category_sections
    [
      ["aAdvisory", "None", "baton_rouge/news"],
      ["aAdvisory", "zNone", "baton_rouge/news"],
      ["Acadiana", "None", "acadiana/news"],
      ["Acadiana", "Column", "acadiana/news"],
      ["Acadiana", "Police-Fire", "acadiana/news/crime/police"],
      ["Acadiana", "Education", "acadiana/news/education"],
      ["Acadiana", "", "acadiana/news"],
      ["Acadiana", "Weather", "acadiana/news/weather/traffic"],
      ["Acadiana", "Traffic", "acadiana/news/weather/traffic"],
      ["Acadiana", "General", "acadiana/news"],
      ["Acadiana", "Elections", "acadiana/news/politics/elections"],
      ["Acadiana", "General-Not Latest", "acadiana/news"],
      ["Ascension Weekly", "None", "baton_rouge/news/communities/ascension"],
      ["Ascension Weekly", "General", "baton_rouge/news/communities/ascension"],
      ["Baker", "None", "baton_rouge/news/communities/baker"],
      ["Baker", "Police-Fire", "baton_rouge/news/communities/baker"],
      ["Baker", "Column", "baton_rouge/news/communities/baker"],
      ["Baker", "Education", "baton_rouge/news/communities/baker"],
      ["Baker", "Weather", "baton_rouge/news/communities/baker"],
      ["Baker", "Traffic", "baton_rouge/news/communities/baker"],
      ["Baker", "General", "baton_rouge/news/communities/baker"],
      ["Baker", "Elections", "baton_rouge/news/communities/baker"],
      ["Baker", "General-Not Latest", "baton_rouge/news/communities/baker"],
      ["Beaucoup", "", "new_orleans/entertainment/life"],
      ["Beaucoup", "General", "new_orleans/entertainment/life"],
      ["Beaucoup", "Arts", "new_orleans/entertainment/life/arts"],
      ["Beaucoup", "Movies", "new_orleans/entertainment/life/movies/tv"],
      ["Beaucoup", "Music", "new_orleans/entertainment/life/music"],
      ["Beaucoup", "Food-Restaurants", "new_orleans/entertainment/life/food_restaurants"],
      ["BeFitBR", "None", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Articles", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Calendar", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Dining", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Fitness Finds", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Health and Beauty", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Recipes", "baton_rouge/enterainment/life/health_fitness"],
      ["BeFitBR", "Workout Routines", "baton_rouge/enterainment/life/health_fitness"],
      ["Business", "None", "baton_rouge/news/business"],
      ["Business", "Column", "baton_rouge/news/business"],
      ["Business", "General", "baton_rouge/news/business"],
      ["Business", "General-Not Latest", "baton_rouge/news/business"],
      ["City", "None", "baton_rouge/news"],
      ["City", "Police-Fire", "baton_rouge/news/crime/police"],
      ["City", "Central", "baton_rouge/news"],
      ["City", "Education", "baton_rouge/news/education"],
      ["City", "Weather", "batonrouge/news/weather/traffic"],
      ["City", "Traffic", "batonrouge/news/weather/traffic"],
      ["City", "Column", "batonrouge/opinion"],
      ["City", "General", "baton_rouge/news"],
      ["City", "Elections", "baton_rouge/news/politics/elections"],
      ["City", "General-Not Latest", "baton_rouge/news"],
      ["Classified", "None", "baton_rouge"],
      ["Classified", "Wheels", "baton_rouge"],
      ["Classified", "Homes", "baton_rouge"],
      ["Classified", "Jobs", "baton_rouge"],
      ["Classified", "Column", "baton_rouge"],
      ["Classified", "NOLegals", "new_orleans"],
      ["CNB", "None", "baton_rouge/news/politics"],
      ["CNB", "Politics", "baton_rouge/news/politics"],
      ["CNB", "Legislature", "baton_rouge/news/politics/legislature"],
      ["CNB", "Elections", "baton_rouge/news/politics/elections"],
      ["CNB", "Education", "baton_rouge/news/education"],
      ["CNB", "Washington", "baton_rouge/news/politics"],
      ["CNB", "Column", "baton_rouge/opinion"],
      ["CNB", "General", "baton_rouge/news/politics"],
      ["CNB", "General-Not Latest", "baton_rouge/news/politics"],
      ["Column", "None", "baton_rouge/opinion"],
      ["Column", "Mark Ballard", "baton_rouge/opinion/mark_ballard"],
      ["Column", "Smiley Anders", "baton_rouge/entertainment/life"],
      ["Column", "zzEd Cullen", "baton_rouge/opinion"],
      ["Column", "Danny Heitman", "baton_rouge/entertainment/life/danny_heitman"],
      ["Column", "zzGerard Sheilds", "baton_rouge/opinion"],
      ["Column", "zzBob Anderson", "baton_rouge/opinion"],
      ["Column", "Pam Bordelon", "baton_rouge/entertainment/life/pam_bordelon"],
      ["Column", "Terry Robinson", "baton_rouge/entertainment/life/terry_robinson"],
      ["Column", "Leila Pitchford-English", "baton_rouge/entertainment/life/leila_pitchford-english"],
      ["Column", "zzCarl Redman", "baton_rouge/opinion"],
      ["Column", "Joe Macaluso", "baton_rouge/sports/outdoors"],
      ["Column", "Pat Shingleton", "baton_rouge/news/weather/traffic"],
      ["Column", "Cheramie Sonnier", "baton_rouge/entertainment/life/food_restaurants"],
      ["Column", "zzJordan Blum", "baton_rouge/opinion"],
      ["Column", "Chante Warren", "baton_rouge/opinion"],
      ["Column", "James Gill", "new_orleans/opinion/james_gill"],
      ["Column", "Stephanie Grace", "baton_rouge/opinion/stephanie_grace"],
      ["Column", "Ed Pratt", "baton_rouge/opinion/ed_pratt"],
      ["Column", "Dennis Persica", "new_orleans/opinion/dennis_persica"],
      ["Column", "zzEditorial", "baton_rouge/opinion"],
      ["Column", "Steven Forster", "new_orleans/entertainment/life/steven_forster"],
      ["Column", "Nell Nolan", "new_orleans/entertainment/life/nell_nolan"],
      ["Column", "Patricia Gannon", "acadiana/entertainment/life/patricia_gannon"],
      ["Column", "Scott Rabalais", "baton_rouge/sports/scott_rabalais"],
      ["Column", "Quin Hillyer", "baton_rouge/opinion"],
      ["Column", "Gregory Roberts", "baton_rouge/opinion"],
      ["Column", "LannyKeller", "baton_rouge/opinion"],
      ["Column", "Josh Eachus", "baton_rouge/news/weather/traffic"],
      ["East Feliciana", "", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Column", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Community", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Education", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Elections", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "General", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "General Not For Latest", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Police-Fire", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Traffic", "baton_rouge/news/east_feliciana"],
      ["East Feliciana", "Weather", "baton_rouge/news/east_feliciana"],
      ["EPL-Both", "Food-Restaurant", "baton_rouge/entertainment/life"],
      ["EPL-Both", "General", "baton_rouge/entertainment/life"],
      ["EPL-BR", "", "baton_rouge/entertainment/life"],
      ["EPL-BR", "General", "baton_rouge/entertainment/life"],
      ["EPL-BR", "Home-Garden", "baton_rouge/entertainment/life/home/garden"],
      ["EPL-BR", "Faith", "baton_rouge/entertainment/life/faith"],
      ["EPL-BR", "Health-Fitness", "baton_rouge/entertainment/life/health_fitness"],
      ["EPL-BR", "Recipes", "baton_rouge/entertainment/life/food_restaurants"],
      ["EPL-BR", "Arts", "baton_rouge/entertainment/life/arts"],
      ["EPL-BR", "Books", "baton_rouge/entertainment/life/books"],
      ["EPL-BR", "Movies-TV", "baton_rouge/entertainment/life/movies/tv"],
      ["EPL-BR", "Music", "baton_rouge/entertainment/life/music"],
      ["EPL-BR", "Travel", "baton_rouge/entertainment/life/travel"],
      ["EPL-NO", "", "new_orleans/entertainment/life"],
      ["EPL-NO", "General", "new_orleans/entertainment/life"],
      ["EPL-NO", "Travel", "new_orleans/entertainment/life"],
      ["EPL-NO", "Food-Restaurants", "new_orleans/entertainment/life"],
      ["EPL-NO", "Home-Garden", "new_orleans/entertainment/life/home/garden"],
      ["EPL-NO", "Health-Fitness", "new_orleans/entertainment/life/health_fitness"],
      ["EPL-NO", "Books", "new_orleans/entertainment/life/books"],
      ["EPL-NO", "Arts", "new_orleans/entertainment/life/arts"],
      ["EPL-NO", "Movies-TV", "new_orleans/entertainment/life/movies/tv"],
      ["EPL-NO", "Music", "new_orleans/entertainment/life/music"],
      ["Extra", "", "baton_rouge/news"],
      ["Extra", "General", "baton_rouge/news"],
      ["Florida Parishes", "None", "baton_rouge/news/communities"],
      ["Florida Parishes", "Police-Fire", "baton_rouge/news/communities"],
      ["Florida Parishes", "Column", "baton_rouge/news/communities"],
      ["Florida Parishes", "Education", "baton_rouge/news/communities"],
      ["Florida Parishes", "Weather", "baton_rouge/news/communities"],
      ["Florida Parishes", "Traffic", "baton_rouge/news/communities"],
      ["Florida Parishes", "General", "baton_rouge/news/communities"],
      ["Florida Parishes", "Elections", "baton_rouge/news/communities"],
      ["Florida Parishes", "General-Not Latest", "baton_rouge/news/communities"],
      ["Jefferson", "", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "General", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Crime-Courts", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Politics-Government", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Education", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Business", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Community", "new_orleans/news/communities/east_jefferson"],
      ["Jefferson", "Election", "new_orleans/news/communities/east_jefferson"],
      ["LivTanWeekly", "None", "baton_rouge/news/communities/livingston/tangipahoa"],
      ["LivTanWeekly", "General", "baton_rouge/news/communities/livingston/tangipahoa"],
      ["Marketing", "None", "baton_rouge/news"],
      ["Marketing", "Special Sections", "baton_rouge/news"],
      ["Marketing", "General", "baton_rouge/news"],
      ["MidCity Weekly", "", "baton_rouge/communities/mid_city"],
      ["MidCity Weekly", "General", "baton_rouge/communities/mid_city"],
      ["MidCity Weekly", "", "baton_rouge/communities/mid_city"],
      ["New Orleans", "None", "new_orleans/news"],
      ["New Orleans", "Column", "new_orleans/opinion"],
      ["New Orleans", "Education", "new_orleans/news/education"],
      ["New Orleans", "General", "new_orleans/news"],
      ["New Orleans", "Crime-Courts", "new_orleans/news"],
      ["New Orleans", "Politics-Government", "new_orleans/politics"],
      ["New Orleans", "Business", "new_orleans/news/business"],
      ["New Orleans", "Community", "new_orleans/news"],
      ["New Orleans", "Election", "new_orleans/news/politics/elections"],
      ["NIE", "None", "baton_rouge"],
      ["NIE", "Childrens Pages", "baton_rouge"],
      ["NIE", "Lousiana Pages", "baton_rouge"],
      ["None", "None", "baton_rouge"],
      ["Online", "None", "baton_rouge/news"],
      ["Online", "News", "baton_rouge/news"],
      ["Online", "Sports", "baton_rouge/news"],
      ["Online", "Features", "baton_rouge/news"],
      ["Online", "Column", "baton_rouge/news"],
      ["Online", "The Advocate", "baton_rouge/news"],
      ["Online", "Traffic", "baton_rouge/news"],
      ["Online", "Weather", "baton_rouge/news"],
      ["Online", "Entertainment", "baton_rouge/news"],
      ["Opinion", "", "baton_rouge/news/opinon"],
      ["Opinion", "Editorial", "baton_rouge/opinion/our_views"],
      ["Opinion", "zzViewpoint", "baton_rouge/opinion"],
      ["Opinion", "Letters to the Editor", "baton_rouge/opinion/letters"],
      ["Opinion", "Inside Report", "baton_rouge/opinion"],
      ["Opinion", "General", "baton_rouge/opinion"],
      ["Opinion", "zzStephanie Grace", "baton_rouge/opinion/stephanie_grace"],
      ["Opinion", "zzDennis Persica", "new_orleans/opinion/dennis_persica"],
      ["Opinion", "zzJames Gill", "new_orleans/opinon/james_gill"],
      ["Opinion", "Walt Handelsman - BR", "baton_rouge/opinion/walt_handelsman"],
      ["Opinion", "Walt Handlesman - NO", "new_orleans/opinion/walt_handelsman"],
      ["Photos", "None", "baton_rouge/news"],
      ["Photos", "LSU Football", "baton_rouge/sports/lsu"],
      ["Photos", "LSU", "baton_rouge/sports/lsu"],
      ["Photos", "SU Sports", "baton_rouge/sports/southern"],
      ["Photos", "Ascension", "baton_rouge/news/communities/ascension"],
      ["Photos", "BR Prep", "baton_rouge/sports/high_schools"],
      ["Photos", "Saints", "new_orleans/sports/saints"],
      ["Photos", "BR Features", "baton_rouge/news"],
      ["Photos", "BR General", "baton_rouge/news"],
      ["Photos", "Weather", "baton_rouge/news/weather/traffic"],
      ["Photos", "Pelicans", "new_orleans/sports/pelicans"],
      ["Photos", "New Orleans Preps", "new_orleans/sports/high_schools"],
      ["Photos", "New Orleans Colleges", "new_orleans/sports"],
      ["Photos", "New Orleans General", "new_orleans/news"],
      ["Photos", "NO Features", "new_orleans/entertainment/life"],
      ["Photos", "Acadiana", "acadiana/news"],
      ["Red", "None", "baton_rouge/entertainment/life"],
      ["Red", "Restaurant Reviews", "baton_rouge/entertainment/life/food_restaurants"],
      ["Red", "Movie News", "baton_rouge/entertainment/life/movies/tv"],
      ["Red", "Music", "baton_rouge/entertainment/life/music"],
      ["Red", "Entertainment", "baton_rouge/enterainment/life"],
      ["Red", "Video Games", "baton_rouge/enterainment/life"],
      ["Red", "Band Directory", "baton_rouge/enterainment/life/music"],
      ["Red", "Calendars", "baton_rouge/enterainment/life"],
      ["Red", "Column", "baton_rouge/enterainment/life"],
      ["Red", "Mixed Martial Arts", "baton_rouge/enterainment/life"],
      ["Red", "Movie Reviews", "baton_rouge/entertainment/life/movies/tv"],
      ["Red", "Video", "baton_rouge/enterainment/life"],
      ["Red", "General", "baton_rouge/enterainment/life"],
      ["River Parishes", "None", "new_orleans/news/communities"],
      ["River Parishes", "Police-Fire", "new_orleans/news/communities"],
      ["River Parishes", "Column", "new_orleans/news/communities"],
      ["River Parishes", "Education", "new_orleans/news/communities"],
      ["River Parishes", "Weather", "new_orleans/news/communities"],
      ["River Parishes", "Traffic", "new_orleans/news/communities"],
      ["River Parishes", "General", "new_orleans/news/communities"],
      ["River Parishes", "Election", "new_orleans/news/communities"],
      ["Southeast Weekly", "", "baton_rouge/news/communities/southeast"],
      ["Southeast Weekly", "None", "baton_rouge/news/communities/southeast"],
      ["Southeast Weekly", "General", "baton_rouge/news/communities/southeast"],
      ["Southside Weekly", "", "baton_rouge/news/communities/southeast"],
      ["Southside Weekly", "None", "baton_rouge/news/communities/southeast"],
      ["Southside Weekly", "General", "baton_rouge/news/communities/southeast"],
      ["Special Sections", "None", "baton_rouge"],
      ["Special Sections", "Football", "baton_rouge"],
      ["Sports", "None", "new_orleans/sports"],
      ["Sports", "LSU", "baton_rouge/sports/lsu"],
      ["Sports", "Southern", "baton_rouge/sports/southern"],
      ["Sports", "Area Colleges", "new_orleans/sports"],
      ["Sports", "Saints", "new_orleans/sports/saints"],
      ["Sports", "Pelicans", "new_orleans/sports/pelicans"],
      ["Sports", "High Schools", "new_orleans/sports/high_schools"],
      ["Sports", "Outdoors", "baton_rouge/sports/outdoors"],
      ["Sports", "Mixed Martial Arts", "new_orleans/sports"],
      ["Sports", "General", "new_orleans/sports"],
      ["Sports", "LSU Football", "baton_rouge/sports/lsu"],
      ["Sports", "SU Football", "baton_rouge/sports"],
      ["Sports", "Preps Football", "new_orleans/sports/high_schools"],
      ["Sports", "State Schools Football", "new_orleans/sports"],
      ["Sports", "Recruiting Football", "new_orleans/sports"],
      ["Sports", "New Orleans Prep", "new_orleans/sports/high_schools"],
      ["Sports", "Tulane", "new_orleans/sports/tulane"],
      ["Sports", "UL-Lafayette", "acadiana/sports/ullafayette"],
      ["Sports", "Zephyrs", "new_orleans/sports/zephyrs"],
      ["Sports", "UL Football", "acadiana/sports/ullafayette"],
      ["Sports", "Acadiana Prep", "acadiana/sports/high_school_sports"],
      ["Sports", "Fair Grounds", "new_orleans/sports/horse_racing"],
      ["St Helena", "", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Column", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Community", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Education", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Elections", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "General", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "General Not For Latest", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Police-Fire", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Traffic", "baton_rouge/news/communities/st_helena"],
      ["St Helena", "Weather", "baton_rouge/news/communities/st_helena"],
      ["St Tammany", "", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "General", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Crime-Courts", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Politics-Government", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Education", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Business", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Community", "new_orleans/news/community/st_tammany"],
      ["St Tammany", "Elections", "new_orleans/news/community/st_tammany"],
      ["Temporary", "None", "baton_rouge/news"],
      ["Video", "None", "baton_rouge/news"],
      ["Video", "News BR", "baton_rouge/news"],
      ["Video", "Sports BR", "baton_rouge/sports"],
      ["Video", "Entertainment BR", "baton_rouge/entertainment_life"],
      ["Video", "Features BR", "baton_rouge/entertainment_life"],
      ["Video", "Entertainment NO", "new_orleans/entertainment_life"],
      ["Video", "Features NO", "new_orleans/entertainment_life"],
      ["Video", "News NO", "new_orleans/news"],
      ["Video", "Sports NO", "new_orleans/sports"],
      ["Video", "Saints-LSU", "new_orleans/sports"],
      ["West Feliciana", "", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Column", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Community", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Education", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Elections", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "General", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "General Not For Latest", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Police-Fire", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Traffic", "baton_rouge/news/communities/westfeliciana"],
      ["West Feliciana", "Weather", "baton_rouge/news/communities/westfeliciana"],
      ["Westside", "None", "baton_rouge/news/communities/westside"],
      ["Westside", "Police-Fire", "baton_rouge/news/communities/westside"],
      ["Westside", "Column", "baton_rouge/news/communities/westside"],
      ["Westside", "Education", "baton_rouge/news/communities/westside"],
      ["Westside", "Weather", "baton_rouge/news/communities/westside"],
      ["Westside", "Traffic", "baton_rouge/news/communities/westside"],
      ["Westside", "General", "baton_rouge/news/communities/westside"],
      ["Westside", "Elections", "baton_rouge/news/communities/westside"],
      ["Westside", "General-Not Latest", "baton_rouge/news/communities/westside"],
      ["Wire Business", "None", "nation/world"],
      ["Wire Business", "Agriculture", "nation/world"],
      ["Wire Business", "Economy", "nation/world"],
      ["Wire Business", "Energy", "nation/world"],
      ["Wire Business", "Finance", "nation/world"],
      ["Wire Business", "Markets", "nation/world"],
      ["Wire Business", "Real Estate", "nation/world"],
      ["Wire Business", "Retail", "nation/world"],
      ["Wire Business", "Technology", "nation/world"],
      ["Wire Business", "Advance", "nation/world"],
      ["Wire Business", "zNone", "nation/world"],
      ["Wire Features", "None", "nation/world"],
      ["Wire Features", "Books", "nation/world"],
      ["Wire Features", "Entertainment", "nation/world"],
      ["Wire Features", "Family", "nation/world"],
      ["Wire Features", "Fashion", "nation/world"],
      ["Wire Features", "Film", "nation/world"],
      ["Wire Features", "Food", "nation/world"],
      ["Wire Features", "Health", "nation/world"],
      ["Wire Features", "Home and Garden", "nation/world"],
      ["Wire Features", "Music", "nation/world"],
      ["Wire Features", "Religion", "nation/world"],
      ["Wire Features", "Technology", "nation/world"],
      ["Wire Features", "Travel", "nation/world"],
      ["Wire Features", "zNone", "nation/world"],
      ["Wire Features", "Horoscopes", "nation/world"],
      ["Wire Features", "Restaurants", "nation/world"],
      ["Wire Features", "Recipes", "nation/world"],
      ["Wire Features", "Teens and Kids", "nation/world"],
      ["Wire Features", "Arts", "nation/world"],
      ["Wire Features", "Fun", "nation/world"],
      ["Wire Features", "Games", "nation/world"],
      ["Wire News", "None", "nation/world"],
      ["Wire News", "National", "nation/world"],
      ["Wire News", "Politics", "nation/world"],
      ["Wire News", "World", "nation/world"],
      ["Wire News", "Local", "nation/world"],
      ["Wire News", "State and Region", "nation/world"],
      ["Wire News", "Washington", "nation/world"],
      ["Wire News", "Weather", "nation/world"],
      ["Wire News", "Education", "nation/world"],
      ["Wire News", "Legislature", "nation/world"],
      ["Wire News", "Police", "nation/world"],
      ["Wire News", "Home Page", "nation/world"],
      ["Wire Sports", "None", "nation/world"],
      ["Wire Sports", "Agate", "nation/world"],
      ["Wire Sports", "Boxing", "nation/world"],
      ["Wire Sports", "Baseball-AL", "nation/world"],
      ["Wire Sports", "College", "nation/world"],
      ["Wire Sports", "Baseball-College", "nation/world"],
      ["Wire Sports", "Baseball-MLB", "nation/world"],
      ["Wire Sports", "Golf", "nation/world"],
      ["Wire Sports", "High School", "nation/world"],
      ["Wire Sports", "Horse Racing", "nation/world"],
      ["Wire Sports", "Baseball-NL", "nation/world"],
      ["Wire Sports", "Baseball-Other", "nation/world"],
      ["Wire Sports", "Basketball-College Men", "nation/world"],
      ["Wire Sports", "Basketball-College Women", "nation/world"],
      ["Wire Sports", "Basketball-NBA", "nation/world"],
      ["Wire Sports", "Basketball-Other", "nation/world"],
      ["Wire Sports", "Cycling", "nation/world"],
      ["Wire Sports", "Football-College", "nation/world"],
      ["Wire Sports", "Football-NFL", "nation/world"],
      ["Wire Sports", "Football-Other", "nation/world"],
      ["Wire Sports", "Hockey-Other", "nation/world"],
      ["Wire Sports", "Motor Sports", "nation/world"],
      ["Wire Sports", "Outdoors", "nation/world"],
      ["Wire Sports", "Hockey-NHL", "nation/world"],
      ["Wire Sports", "Olympics", "nation/world"],
      ["Wire Sports", "Winter Sports", "nation/world"],
      ["Wire Sports", "Tennis", "nation/world"],
      ["Wire Sports", "Track", "nation/world"],
      ["Wire Sports", "Soccer", "nation/world"],
      ["Wire Sports", "None", "nation/world"],
      ["Wire Sports", "LSU", "nation/world"],
      ["Wire Sports", "Saints", "nation/world"],
      ["Wire Sports", "Hornets", "nation/world"],
      ["Wire Sports", "Southern", "nation/world"],
      ["Zachary", "", "baton_rouge/news/communities/zachary"],
      ["Zachary", "General", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Column", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Community", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Education", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Elections", "baton_rouge/news/communities/zachary"],
      ["Zachary", "General Not For Latest", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Police Fire", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Traffic", "baton_rouge/news/communities/zachary"],
      ["Zachary", "Weather", "baton_rouge/news/communities/zachary"],
      ["zzFeatures", "None", "baton_rouge/entertainment_life"],
      ["zzFeatures", "Food", "baton_rouge/entertainment_life/food_restaurants"],
      ["zzFeatures", "Music", "baton_rouge/entertainment_life/music"],
      ["zzFeatures", "Highlight", "baton_rouge/entertainment_life"],
      ["zzFeatures", "Movies", "baton_rouge/entertainment_life/movies_tv"],
      ["zzFeatures", "Arts", "baton_rouge/entertainment_life/arts"],
      ["zzFeatures", "Carnival", "baton_rouge/entertainment_life/mardi_gras"],
      ["zzFeatures", "HealthFitness", "baton_rouge/entertainment_life/health_fitness"],
      ["zzFood", "None", "baton_rouge/entertainment_life/food_restaurants"],
      ["zzFood", "Recipes", "baton_rouge/entertainment_life/food_restaurants"],
      ["zzFood", "Column", "baton_rouge/entertainment_life/food_restaurants"],
      ["zzFood", "General", "baton_rouge/entertainment_life/food_restaurants"],
      ["zzMagazine", "None", "baton_rouge/entertainment_life"],
      ["zzMagazine", "Art", "baton_rouge/entertainment_life/arts"],
      ["zzMagazine", "Books", "baton_rouge/entertainment_life/books"],
      ["zzMagazine", "Travel", "baton_rouge/entertainment_life/travel"],
      ["zzMagazine", "Music", "baton_rouge/entertainment_life/music"],
      ["zzMagazine", "Theater", "baton_rouge/entertainment_life/arts"],
      ["zzMagazine", "Calendars", "baton_rouge/entertainment_life"],
      ["zzMagazine", "Column", "baton_rouge/entertainment_life"],
      ["zzMagazine", "General", "baton_rouge/entertainment_life"],
      ["zzPeople", "None", "baton_rouge/entertainment_life"],
      ["zzPeople", "Faith", "baton_rouge/entertainment_life/faith"],
      ["zzPeople", "Party Scene", "baton_rouge/entertainment_life"],
      ["zzPeople", "Teens-Kids", "baton_rouge/entertainment_life"],
      ["zzPeople", "Military", "baton_rouge/entertainment_life"],
      ["zzPeople", "Gardening-Decor", "baton_rouge/entertainment_life/home_garden"],
      ["zzPeople", "Style", "baton_rouge/entertainment_life"],
      ["zzPeople", "Weddings", "baton_rouge/entertainment_life"],
      ["zzPeople", "Engagements", "baton_rouge/entertainment_life"],
      ["zzPeople", "Anniversary", "baton_rouge/entertainment_life"],
      ["zzPeople", "Column", "baton_rouge/entertainment_life"],
      ["zzPeople", "General", "baton_rouge/entertainment_life"]
    ]
  end
end
